language: c

git:
  depth: false

services:
  - docker

jobs:
  include:
    - name: "Build Test"
      before_install: docker pull thesofproject/sof && docker tag thesofproject/sof sof
      script:
        - echo -e '#!/bin/bash\nmkdir build && cd build && cmake .. && make -Werror -Wall -Wmissing-prototypes -Wimplicit-fallthrough=3 -Wpointer-arith' > build.sh && chmod +x build.sh
        - docker run -i -t -v $(pwd):/home/sof/work/sof.git --user $(id -u) sof ./build.sh
    - name: checkpatch
      before_install:
        - sudo apt-get -y install codespell
      script:
        - git --no-pager log --oneline --graph --decorate --max-count=5
        - git --no-pager log --oneline --graph --decorate --max-count=5 "${TRAVIS_BRANCH}"
        - (set -x; scripts/checkpatch.pl --no-tree --strict --codespell --no-signoff -g ${TRAVIS_COMMIT_RANGE/.../..})
